### ISSUE TITLE
⚡ Feature | Blog roll

### ISSUE THREAD

**Issue by friedger** [pradel/sigle#145]
## Description
It would be nice to add a list of friends' blogs who published their blog via a contract call.

1. Add list of user names in my blog meta data 
1. Add smart contract (public registry) 
1. Add publish on chain button
1. Add ui in blog to link to other blogs

**Comment by pradel** [comment]
@friedger I am not sure I fully understand this. You would like the ability to link other blogs to yours? Didn't really understand point 2.

**Comment by pradel** [comment]
I am closing this one, the idea is to have a discover page that let you see all the content written on Sigle easily.
