### ISSUE TITLE
Clicking on the eyeball icon next to the Blockstack.id before publishing the first sigle 404s

### ISSUE THREAD

**Issue by AC-FTW** [pradel/sigle#15]
Before publishing my first sigle (or writing / drafting one), I clicked on the eyeball icon next to my blockstack ID on the top right. I was taken to a pretty cool 404 page that said "Julia has gone too far". I suspect on login/account creation it should create a blank placeholder page saying something like 'your published sigles will show up here'.

**Comment by pradel** [comment]
You are right would be better to see the user page with an empty story list rather than 404 in that case 👍
