### ISSUE TITLE
🐛 Bug |  Sigle doesn't seem to show up after being published.

### ISSUE THREAD

**Issue by AC-FTW** [pradel/sigle#16]
I was able to draft and save my sigle. Then I clicked publish and it said it published it, however, it didn't show up in the Published tab (the count was still zero) and when I click on the eyeball, I no longer get the 404, but I don't see any content -- just tabs saying my blockstack id and 'Stories'.

I'm wondering if this isn't Sigle, but the fact that Blockstack is failing for the ID that I was using (alex.stealthy.id). I'll try another account and get back to you.

**Comment by AC-FTW** [comment]
Yup--the domain is the problem--my non subdomain ID publishes fine. I suspect this is a Blockstack infrastructure issue (though you might have an unhandled error/promise rejection going on too.

**Comment by pradel** [comment]
Hey, thanks for the report! Would you mind checking the dev console if you see any error that can help me to debug that ? :)

**Comment by AC-FTW** [comment]
I logged in as alex.stealthy.id and clicked on one of my sigle's and saw the following:

StoryItem.tsx:24 Error: Story is already public
    at index.ts:72
    at w (runtime.js:63)
    at Generator._invoke (runtime.js:282)
    at Generator.e.(/anonymous function) [as next] (https://app.sigle.io/static/js/2.8e7bca52.chunk.js:1:991456)
    at n (asyncToGenerator.js:3)
    at s (asyncToGenerator.js:25)

However, when I look at published, it reports 0 and when I go to my sigle public / visible page, it's empty.

Then I thought it might help if I create a new sigle and show you the console when I try to make it public from that account. There is no error--it just doesn't show up as public for some reason--here's the console log:

[DEBUG] uploadToGaiaHub: uploading stories.json to https://hub.blockstack.org
logger.js:71 [DEBUG] uploadToGaiaHub: uploading publicStories.json to https://hub.blockstack.org
logger.js:71 [DEBUG] uploadToGaiaHub: uploading dycVKORZVyzqm2_hrtKDS.json to https://hub.blockstack.org
logger.js:71 [DEBUG] uploadToGaiaHub: uploading dycVKORZVyzqm2_hrtKDS.json to https://hub.blockstack.org
logger.js:71 [DEBUG] uploadToGaiaHub: uploading stories.json to https://hub.blockstack.org
logger.js:71 [DEBUG] uploadToGaiaHub: uploading publicStories.json to https://hub.blockstack.org
logger.js:71 [DEBUG] uploadToGaiaHub: uploading stories.json to https://hub.blockstack.org
logger.js:71 [DEBUG] uploadToGaiaHub: uploading publicStories.json to https://hub.blockstack.org
logger.js:71 [DEBUG] uploadToGaiaHub: uploading dycVKORZVyzqm2_hrtKDS.json to https://hub.blockstack.org

If I had to guess, it's either a Blockstack issue with the stealthy.id subdomain or an issue in your code handling TLDs on different subdomains--not sure as I haven't perused your source much. Hope this helps 👍

**Comment by AC-FTW** [comment]
Also when I go to the GAIA bucket for alex.stealthy.id and look for that json, I'm seeing it:

https://gaia.blockstack.org/hub/136c1bn6jkbBVBFyU5SKhamBADYTPaqEft/dycVKORZVyzqm2_hrtKDS.json

It also shows up in the public page:

https://gaia.blockstack.org/hub/136c1bn6jkbBVBFyU5SKhamBADYTPaqEft/publicStories.json

It just doesn't show up on the My Stories page under Published (so it's probably just a logic thing to flush out in the code on the My Stories Page):

![image](https://user-images.githubusercontent.com/16608312/53122634-e5edf380-350b-11e9-815a-7d63181908ae.png)

**Comment by pradel** [comment]
Closing this one as it seems to be solved from the last tests
