### ISSUE TITLE
⚡ Feature | 

### ISSUE THREAD

**Issue by dikkuzfaye** [pradel/sigle#168]
Sorry for opening the topic here, I did not want to open dc account for this. New user here. How can i share my blog with others? Is there a link for this or etc.? You can delete my issue 1 day later after answering to not cause inappropriate flow of issuesm

**Comment by pradel** [comment]
Hey, to get your account URL, go to the dashboard and on the top right corner you have a visit my blog button that will give you the URL to share.

**Comment by dikkuzfaye** [comment]
It looks like I dont get anything from clicking it?  It just opens my dashborad again. Maybe it doesnt work in android. Android 10, Bromite browser.

**Comment by dikkuzfaye** [comment]
Btw I will not publish a blog but wanted to inform you because it is open source.
