### ISSUE TITLE
🐛 Bug | Visit my blog button does not work

### ISSUE THREAD

**Issue by Ndawakh** [pradel/sigle#201]
## Description

When I click the "visit my blog" button it will open another tab of the same thing I was looking up (check video below to understand what I mean)
I am not sure if this is a bug or I am doing something wrong.. I have tried resting my browser setting, removing extensions, writing fake articles,  but the problem still exist.

https://user-images.githubusercontent.com/83010966/117240451-ba276180-ae28-11eb-97db-8c5894ec3bec.mp4

 
## Device

- OS: Linux Ubuntu
- Browser: Brave/ Firefox too
- Version: both latest version

**Comment by pradel** [comment]
Hey, you did nothing wrong, it's related to a blockstack issue. Sorry for the inconvenience, you can subscribe to this thread to see the progress https://github.com/blockstack/stacks.js/issues/1016. Really hope it can be solved soon! Will keep you updated here once it's solved.

**Comment by pradel** [comment]
Hey, the issue is finally solved so you can now create a new account with a new username and everything should work :)
