### ISSUE TITLE
Redesign editor page: General layout

### ISSUE THREAD

**Issue by pradel** [pradel/sigle#274]
## Description

Redesign the layout of the current editor page to match the new theme.

![Capture d’écran 2022-01-17 à 09 51 55](https://user-images.githubusercontent.com/5749437/149737753-daf456d4-23dd-49c9-9c9f-96f1b7945dfc.png)

In order to be fully responsive might be a good idea to set a max length that truncate the name

Notes:

- On the bottom right side the word count will be implemented only when the new Editor made with TipTap will be ready https://github.com/pradel/sigle/issues/188.
- On the bottom right the keyboard shortcuts helper can be done in a separate pull request once the design are ready https://github.com/pradel/sigle/issues/276.

### Needs clarification

5. On the top left corner, if the user didn't set a custom blog name, do we show the .id.stx name ?

**Comment by gregogun** [comment]
Just a couple of questions so I'm fully clear on the task: 

1. Regarding the word count and keyboard shortcuts implementation being blocked, I just wanted to clarify that should they be left out of the UI at this point?
2. I've noticed there's a new design for the toast component to the current implementation. Will this change need to be made as part of this PR, or can it be done separately?
3. Lastly, just to verify that the back arrow is pointing back to the user's dashboard?

Thanks!

**Comment by pradel** [comment]
1. Yup correct 👍 
2. Let's do it separately, I will create a separate issue for this
3. Yup correct 👍
