### ISSUE TITLE
URL's ending in name.id not handled correctly

### ISSUE THREAD

**Issue by fluidvoice** [pradel/sigle#85]
## Description
People with ID's `name.id` versus `name.id.blockstack` result in invalid URL's that give a 502 error
example: **https://app.sigle.io/friedger.id**
Is it that the ".id" needs to be URL encoded?

**Screenshots**
https://imgur.com/uMjoJZw.png

## Device
any

**Comment by fluidvoice** [comment]
now not sure if it's related to domains ending in .id because right now this URL also is not showing up >> https://app.sigle.io/friedger.id/UF470tRdy3BtSs46l7axq
https://imgur.com/Ti5kPGq.png

**Comment by friedger** [comment]
I have updated my postes because they contained cover image data from older
versions. Should be working now.

BBaker <notifications@github.com> schrieb am Sa., 8. Feb. 2020, 11:30:

**Comment by fluidvoice** [comment]
Seems to be working now for my blog page as well. What was the fix? Sigle changed something?

**Comment by pradel** [comment]
Closing since it's resolved now :)
