### ISSUE TITLE
⚡ Feature | CTRL+ K shortcut to add link

### ISSUE THREAD

**Issue by pradel** [pradel/sigle#93]
## Description

Add the CTRL + K shortcut 

As an example slack is doing it this way:

<img width="461" alt="Screenshot 2020-04-27 at 10 16 34" src="https://user-images.githubusercontent.com/5749437/80350000-62970300-8870-11ea-8179-ae9f11516d8b.png">
<img width="586" alt="Screenshot 2020-04-27 at 10 16 15" src="https://user-images.githubusercontent.com/5749437/80350009-63c83000-8870-11ea-9e3b-c66730b91d2a.png">

**Comment by whoabuddy** [comment]
I wanted to add a little more background to this request :smile: 

CTRL + K is a common shortcut used to add, edit, or modify a hyperlink in word processing applications and website management tools.

When pressed, it brings up a dialog requesting more information to set up the link, or to make changes. Below is an example from LibreOffice.

![Screenshot from 2020-02-20 12-15-36](https://user-images.githubusercontent.com/9038904/74969987-d0d7c900-53da-11ea-927e-72bd2c06e6ca.png)

The dialog allows users to enter complex links without having to write the code, and fills in a few related fields for [the anchor tag:](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a)

Some of the items commonly handled by the dialog are:
- automatic addition of protocol at the beginning based on selections
  - i.e. selecting `http` `https` or `ftp` prepends the matching `https://` to the link
  - i.e. selecting `Mail` on the left changes the protocol to `mailto://` and requests the relevant information for that type of link
- automatic addition of link attributes based on [the anchor tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a)
  - i.e. entering name on the screenshot above populates `title=""`

The [documentation](https://help.libreoffice.org/6.4/en-US/text/shared/guide/hyperlink_insert.html) [from](https://help.libreoffice.org/6.4/en-US/text/shared/02/09070000.html) [LibreOffice](https://help.libreoffice.org/6.4/en-US/text/shared/02/09070100.html) covers more of how the dialog above works, but you will have to go through quite a few pages to read it all. :roll_eyes: 

I could not find a de-facto standard for this, but I feel like one has to exist out there. Until another day :coffee:
